### ISSUE TITLE
partial filtering

### ISSUE THREAD

**Issue by cxw-droid** [angel-rs/css-color-filter-generator#11]
Hello, thank you for your work! I have two questions:
1. Is it possible to using the filter without changing the font color (i.e., partially filtering without changing font color)?
2. Is it possible to use filter to change the background color only (instead of using `style.backgroundColor`?

**Comment by angel-rs** [comment]
@cxw-droid 

> 1. Is it possible to using the filter without changing the font color (i.e., partially filtering without changing font color)?

Not as far as I know, the css filter property is a color filter that applies to everything in the element you apply to it.

Haven't tried but maybe you could try overriding the filter of the nested text. It's a hack, but could potentially work.

e.g: 

```
<div ...with filter 1>
  <span ...with filter 2>
```

> 2. Is it possible to use filter to change the background color only (instead of using style.backgroundColor?

Not sure.
I'm only using this for converting images to white, e.g: to render correctly logos when on a dark mode.
Any usage beyond that is out of my knowledge scope.

**Comment by angel-rs** [comment]
As this is not an issue but rather a question, will be closing this one.
