### ISSUE TITLE
Credit stolen code and add LICENSE

### ISSUE THREAD

**Issue by bbb651** [angel-rs/css-color-filter-generator#12]
This seems to be entirely stolen from this [codepen](https://codepen.io/sosuke/pen/Pjoqqp). Codepens are [MIT licensed](https://blog.codepen.io/documentation/licensing/), but it's disrespectful to steal other's code and claim it as your own (by committing it with your name and email), and by having no license you [claim copyright over it](https://choosealicense.com/no-permission/) which is probably not legal, and it would be nice to give it a permissive license regardless, MIT sounds like a good choice.

**Comment by angel-rs** [comment]
Hey @bbb651, thanks for raising this
Will be taking action on the weekend to: 1. add a license to this repo & 2. add proper credit for original author.

Re license: Yeah, the project is MIT, if it was private it wouldn't be in a public repo 🤷

**Comment by angel-rs** [comment]
Added license & credits section ✅
