### ISSUE TITLE
Library idea

### ISSUE THREAD

**Issue by amendezm** [angel-rs/css-color-filter-generator#13]
This could be in a library

```
import {filterFromHex} from "css-color-filter-generator"

const result = filterFromHex("#989898")

<div style={result} />
```

please let me know if I could use this code locally or create the lib myself

**Comment by angel-rs** [comment]
This repo is MIT licensed @amendezm [see here](https://github.com/angel-rs/css-color-filter-generator/issues/12#issuecomment-2121492724) just not actively mantained, feel free to create a library out of it 👍
