### ISSUE TITLE
"Copy" short cut not working

### ISSUE THREAD

**Issue by Sammeeey** [angel-rs/css-color-filter-generator#2]
Hey @angel-rs ✌
The copy short cut doesn't work unfortunately.
If you click it it actually doesn't copy the respective RGB, HEX or filter.

https://user-images.githubusercontent.com/49591562/166093756-a3f19fd3-99af-4e95-980c-d58c81f8819d.mp4

I'd really appreciate if this could be fixed, since I really like the color filter generator tool.🤗

**Comment by angel-rs** [comment]
Hi @Sammeeey :wave: 
That's unfortunate, thank you for flagging :+1: 

Tested on my end & it works as expected

My platform:
Firefox 94.0 (64-bit) - Solus 4.3 Fortitude

https://user-images.githubusercontent.com/20560880/166123784-eee437bf-216b-4522-93ad-51788a9c0c6a.mp4

(sometimes have to click twice, but it works)

What OS/Browser are you using?

This is the [clipboard](https://github.com/zenorocha/clipboard.js/) library used, It should work on all platforms :shrug:

**Comment by Sammeeey** [comment]
I see, it actually works by clicking on the text itself - and not on the *Copy* text.
That's what works for me too.
But it's counterintuitive if you ask me.

I suggest to enable the clipboard when clicking on the *Copy* text too.
Alternatively one could just add a text in the header which says something like *Click on the respective value to copy it* or so.🤔

**Comment by angel-rs** [comment]
> I suggest to enable the clipboard when clicking on the _Copy_ text too.

Agree - that's a better UX.
I can try to squeeze some time during the weekend to give it a go.

If you have the time would appreciate a PR for it.

**Comment by Sammeeey** [comment]
For now I've only made the *copy* visible with #4 
Unfortunately I only know JavaScript basics yet and I don't understand the [`ClipboardJS`](https://github.com/angel-rs/css-color-filter-generator/blob/c42b6d2ac1baf636eaa1f09088d4c5d559330034/index.js#L386).
As far as I understand it's not from the JS standard library (or however they call it in JS😅), but from some external [*clipboard library*](https://github.com/angel-rs/css-color-filter-generator/blob/c42b6d2ac1baf636eaa1f09088d4c5d559330034/index.html#L80) or so!?

**Comment by angel-rs** [comment]
@Sammeeey 

No worries. `ClipboardJS` is a library, so to learn it just need to read the documentation.
Is actually pretty simple, but best to cover javascript basics before diving into that.

I have pushed some changes which should resolve the "copy" text not working.
Please try it out & let me know how it goes.

You can see what I did from my last commits: 

https://github.com/angel-rs/css-color-filter-generator/commits/master

**Comment by Sammeeey** [comment]
Thank you @angel-rs
This works for me now too👌
