### ISSUE TITLE
Website not scrollable

### ISSUE THREAD

**Issue by Sammeeey** [angel-rs/css-color-filter-generator#3]
On my large screen I can see the complete website.
But on my 13" screen I only see that:
![grafik](https://user-images.githubusercontent.com/49591562/166238956-412fbbec-9dea-412b-bd7f-dad8b8711b8e.png)

And there is no scroll bar.

I can however take a screenshot of the complete page (although the lower part is not visible)
![grafik](https://user-images.githubusercontent.com/49591562/166239174-e2087f42-fed0-4d0f-99d8-44d14b29f46a.png)

### OS
Win 10
### Browser
- Chrome 101.0.4951.41
- Firefox 99.0.1 (64-Bit)

**Comment by angel-rs** [comment]
Recently pushed a change. 
It should be scrollable now @Sammeeey 

If it works for you now, please close this issue :+1:

**Comment by Sammeeey** [comment]
Works for me now👌
