### ISSUE TITLE
Color opacity variation

### ISSUE THREAD

**Issue by guilhermeasn** [angel-rs/css-color-filter-generator#8]
Here's a small suggestion: allow you to choose the opacity of the color.
Thanks

**Comment by angel-rs** [comment]
Great suggestion @guilhermeasn !

Unfortunately I don't have the time to add any new features, but if you find value in it & need it, contributions are welcome so feel free to raise a PR adding that.

**Comment by angel-rs** [comment]
As this is not an issue, will be closing this one
